# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WhyNot' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for WhyNot
  pod 'Firebase'
  pod 'FirebaseStorage'
  pod 'FirebaseCore'
  pod 'FirebaseFirestore'
  pod 'FirebaseFirestoreSwift'
  pod 'FirebaseAuth'

end

target 'WhyNotUnitTests' do
  use_frameworks!
  inhibit_all_warnings!

  # Pods for WhyNot
  pod 'Firebase'
  pod 'FirebaseStorage'
  pod 'FirebaseCore'
  pod 'FirebaseFirestore'
  pod 'FirebaseFirestoreSwift'
  pod 'FirebaseAuth'
end
